### ISSUE TITLE
"make" error

### ISSUE THREAD

**Issue by FirePoleR** [cdes5804/NetCut#13]
usr:~/NetCut$ make
mkdir -p bin/models
g++ src/models/scanner.cpp -c -o bin/models/scanner.o -Wall -Wextra -O2 -std=c++17 -I src/
make: g++: No such file or directory
make: *** [Makefile:17: bin/models/scanner.o] Error 127

**Comment by cdes5804** [comment]
Hi! The error indicated that you might not have g++ installed (or the system couldn't find it). It is a tool necessary to compile and build the code.
If you are running Ubuntu, you can try `sudo apt install build-essentials`, which will install g++ along with other commonly used building tools.

**Comment by FirePoleR** [comment]
thanks for the reply, did the build-essential but it outputs unable to locate it, so i tried sudo apt install g++ and now it works, thanks again.

**Comment by cdes5804** [comment]
> thanks for the reply, did the build-essential but it outputs unable to locate it, so i tried sudo apt install g++ and now it works, thanks again.

Nice to hear that!
